### ISSUE TITLE
Can we contribute for translate to Spanish?

### ISSUE THREAD

**Issue by johnfelipe** [maplibre/maputnik#506]
Is possible contribute for translate to Spanish?

**Comment by pathmapper** [comment]
Hi @johnfelipe ,

thanks for the suggestion and your offer. 

I'm not sure what you would like to translate to Spanish:

- editor UI (https://maputnik.github.io/editor/)?
- documentation (e.g. the wiki https://github.com/maputnik/editor/wiki)?
- website (https://maputnik.github.io/)?

Regarding the editor:
The whole [style specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/) is in English and part of the UI (JSON editor, naming of the fields, ...) and I don't think it makes sense to translate these parts because it might be not clear afterwards to which part of the spec something refers.

If we keep everything related to the spec in English, there is not much left to translate.

Also there is currently no functionality implemented to switch the language.

**Comment by 11sma** [comment]
Maybe has sense to translate the helptext when you pass the cursor over fields in the editor. I could collaborate for spanish too. 

But if there's not a way to switch...

**Comment by pathmapper** [comment]
> Maybe has sense to translate the helptext 

These are also taken from the style spec. 
https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec

> I could collaborate for spanish too

@11sma thanks for your offer.

**Comment by HarelM** [comment]
Closing for now, I generally don't see a lot of value in translating the UI, docs might be a different case, but also there I'm not sure there's a real value.
