### ISSUE TITLE
Maplibre & Maputnik

### ISSUE THREAD

**Issue by lseelenbinder** [maplibre/maputnik#788]
Hello, Maputnik friends!

I'm reaching out as a member of the governing board for [MapLibre](https://github.com/maplibre/). I'm curious to see if there's any interest in the Maputnik community for bringing the Maputnik editor under the MapLibre umbrella to align our shared interests and goals. Given the closed-license update of Mapbox GL JS, in my view, Maputnik's primary audience will be as the primary editor for MapLibre styles, and by making that linkage direct, I can see both projects benefiting immensely.

We are seeing a lot of sponsorships and resources being dedicated to maintaining the MapLibre community and projects, and I'm sure that eventually those resources will move towards supporting an editor that works well for testing. In my mind, Maputnik is ideal for this purpose, so if we can begin the process now, we can prepare for the future and ensure the success of both projects (rendering libraries need good style editors and vice versa).

Thanks for your consideration, and I'm happy to answer any questions that might arise from this request!

Best,
Luke

**Comment by nyurik** [comment]
Thanks @lseelenbinder for starting this!  I was actually thinking along the same lines, wondering if Maputnik community would be interested in joining MapLibre, especially because essentially MapLibre is the fullest open source implementation of this styling language.  Going forward, we may even have bounties specifically targeting Maputnik project - so that anyone interested in improving this project might get some financial support too.

Disclaimer:  I am also on the board of MapLibre

**Comment by lseelenbinder** [comment]
As part of this process, I've created the (draft) PR #789  to update the rendering library to the latest version of MapLibre. I think doing this makes sense, regardless of the decision on this idea. 😄

**Comment by nyurik** [comment]
I would love for this to happen, but I prefer to first hear from those the are/were the most active in maintaining this project:   @orangemug @pathmapper and @propheel. Obviously this list won't be complete without @lukasmartinelli :)

Some other contributors who might be interested in commenting:  @gregwolanski @pjsier @jirik @loicgasser @meetar @alicoding

Without your feedback, it won't be right for me to just transfer.  What do you think?

**Comment by wipfli** [comment]
A general discussion about the question if MapLibre should have a style editor can be found at https://github.com/maplibre/maplibre/discussions/153

**Comment by propheel** [comment]
Hey @nyurik and Maputnik community! I just noticed it's been a year since my last contribution! Apologies, lots of personal stuff going on.

Anyways, I really like the idea behind this editor and would like the project to continue. I don't know much about the current direction though or "board members" (it was mainly @orangemug and @pathmapper by then), so don't know who is the one responsible for answering these questions now. Personally I'm fine with either direction provided that it will still be FOSS. And I cannot see much of a difference between this being a separate project maintained by people from MapLibre versus sub-project of MapLibre.

When it comes to my contribution I cannot offer much since I have a bunch of paid side projects going on right now and not enough personal time for proper support here. I am taking a look from time to time though and could help with certain aspects especially around integration infrastructure.

Wish this project gets more traction and community love!

**Comment by HarelM** [comment]
I think this issue can be closed as maputnik is using maplibre now.

**Comment by nyurik** [comment]
Can this be closed now that maputnik has been onboarded?

**Comment by vknoppkewetzel** [comment]
It may be useful to have a message pop up for Maputnik users in the old editor site. I wasn't aware there was a transition (yay!) and when trying to dive back into stylework in Maptunik I was confused about the editor not working and assumed there was work being done and kept circling back later (clearly there was!)

Maybe on `https://maputnik.github.io/editor/#0.8/0/0` page just a simple "Maputnik has moved to MapLibre! head over to this URL instead: `https://maplibre.org/maputnik`"

**Comment by HarelM** [comment]
Feel free to open a PR against the maputnik github io repo, I'm sure it will benefit other users, currently, there's a 404 when you surf to the old editor, which is not a great UX...
