### ISSUE TITLE
Add support for terrain settings

### ISSUE THREAD

**Issue by HarelM** [maplibre/maputnik#828]
Adding the ability to set the terrain source and exaggeration in the editor will allow users to see how the terrain will look.

Notes:
I have started implementing this to see how complicated it is, but saw there there's a bug in maplibre, where you change the style's terrain definition and it doesn't affect (using diff=true).
See: https://github.com/maplibre/maplibre-gl-js/issues/3463
This is a fairly easy issue to solve I believe, but the problem is that this project is using 2.4 and maplibre is nearing 4.0.
Upgrading the dependencies here might prove problematic without typescript support.
I've also started to look into how complicated this would be to add typescript, and due to old usage of webpack and other libraries, this might prove problematic as well.
I've written here a short note about this: #803. 

I guess there's a need to decide where this project is going in order to allow developers to help.

**Comment by nyurik** [comment]
@HarelM thanks for looking at this!  My understanding is that this project is going wherever we take it to go :)  There is substantial interest, but the barrier of entry is high due to long neglect.  Overall, I see these steps as needed, in their approximate order of importance:
* Modernize build setup
* Upgrade dependencies
* Use the latest MapLibre
* Possibly upgrade to TypeScript
* Refactor / improve / add new features

**Comment by HarelM** [comment]
I'll see if #803 will pick off and see if there's a way to migrate some of the code to typescript, otherwise, I don't know how to upgrade maplibre with all the breaking changes without typescript, as I don't know the app good enough to manually test it.

**Comment by HarelM** [comment]
Fixed by 
- #859
